services:
  web:
    container_name: moneyledger-web-dev
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: sh -c "npx prisma generate && npx prisma migrate dev && npm run dev"

  db:
    container_name: moneyledger-db-dev
    volumes:
      - moneyledger_pgdata_dev:/var/lib/postgresql/data

volumes:
  moneyledger_pgdata_dev: